[package]
name = "helldivers_strategem_app"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/MatthewGriffin/helldivers_strategem_app"

[dependencies]
bevy = { version = "0.14.0", features = ["dynamic_linking"] }
